#!/usr/bin/env bash
#
# One-time setup for a fresh Lightsail instance.
#
# Run it once from Lightsail's browser SSH client — no laptop required:
#
#   bash -c "$(curl -fsSL https://raw.githubusercontent.com/dg-dana/home_budget/HEAD/deploy/bootstrap.sh)"
#
# Note the shape: `curl ... | bash` would hand bash the script on stdin, and the
# domain prompt below would then read the script's own next line instead of your
# answer. The prompt reads from /dev/tty to survive that, but the form above is
# the one to copy.
#
# Non-interactive alternative: DOMAIN=budget.example.com bash bootstrap.sh
#
# Afterwards every deploy happens from GitHub Actions.
#
# Installs Docker, creates /opt/home-budget, and generates the session secret.
# Safe to re-run: it never regenerates a secret that already exists, and never
# touches the database.

set -euo pipefail

APP_DIR=/opt/home-budget
ENV_FILE="$APP_DIR/.env"

# $USER is not set by every non-login shell; fall back to the real user.
USER="${USER:-$(id -un)}"

echo "==> Installing Docker (skipped if already present)"
if ! command -v docker > /dev/null 2>&1; then
  curl -fsSL https://get.docker.com | sudo sh
else
  echo "    Docker is already installed."
fi

# So the login user can run docker without sudo on the next session.
if ! id -nG "$USER" | grep -qw docker; then
  sudo usermod -aG docker "$USER"
  echo "    Added $USER to the docker group — log out and back in for it to apply."
fi

echo "==> Ensuring swap exists (skipped if already present)"
# The 512 MB bundle reports ~416 MB usable and Docker, Caddy and the OS take
# most of it. Without swap a small spike has nowhere to go: the live instance
# OOM-killed a process and wedged badly enough to need a force stop. See
# DEPLOY.md §"Memory headroom". Swappiness stays low — this is a safety net,
# not extra capacity.
if swapon --show | grep -q .; then
  echo "    Swap is already active — leaving it alone."
elif [ "$(df -Pk / | awk 'NR==2 {print $4}')" -lt 2097152 ]; then
  echo "    Under 2 GB free on / — skipping swap. Add it by hand later if needed." >&2
else
  sudo fallocate -l 1G /swapfile 2> /dev/null ||
    sudo dd if=/dev/zero of=/swapfile bs=1M count=1024 status=none
  sudo chmod 600 /swapfile
  sudo mkswap /swapfile > /dev/null
  sudo swapon /swapfile
  grep -q '^/swapfile ' /etc/fstab ||
    echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab > /dev/null
  echo 'vm.swappiness=10' | sudo tee /etc/sysctl.d/99-swappiness.conf > /dev/null
  sudo sysctl -q -w vm.swappiness=10
  echo "    Created 1 GB of swap, persisted in /etc/fstab."
fi

echo "==> Creating $APP_DIR"
sudo mkdir -p "$APP_DIR/data"
sudo chown -R "$USER:$USER" "$APP_DIR"

echo "==> Configuring"
if [ -f "$ENV_FILE" ] && grep -q '^JWT_SECRET=' "$ENV_FILE"; then
  echo "    .env already has a JWT_SECRET — leaving it alone."
  echo "    (Changing it would sign every user out.)"
else
  # Read the answer from the terminal, not stdin: stdin may be the script
  # itself if this was piped into bash.
  DOMAIN="${DOMAIN:-}"
  if [ -z "$DOMAIN" ]; then
    if [ -r /dev/tty ]; then
      read -rp "    Domain name for this app (e.g. budget.example.com): " DOMAIN < /dev/tty
    else
      echo "    No terminal to prompt on. Re-run as: DOMAIN=budget.example.com bash bootstrap.sh" >&2
      exit 1
    fi
  fi

  if [ -z "$DOMAIN" ]; then
    echo "    A domain is required: the app sets Secure cookies, so it needs HTTPS." >&2
    exit 1
  fi

  cat > "$ENV_FILE" <<EOF
# Generated by bootstrap.sh. Keep JWT_SECRET stable — changing it invalidates
# every session. APP_IMAGE is rewritten by the deploy workflow.
DOMAIN=$DOMAIN
JWT_SECRET=$(openssl rand -hex 48)
APP_IMAGE=
EOF
  chmod 600 "$ENV_FILE"
  echo "    Wrote $ENV_FILE"
fi

echo
echo "Done. Next:"
echo "  1. Point an A record for your domain at this server's static IP."
echo "  2. Open ports 80 and 443 in the Lightsail Networking tab."
echo "  3. In GitHub: Actions -> Deploy to Lightsail -> Run workflow."
echo
echo "The deploy workflow copies the compose file and Caddyfile here, pulls the"
echo "image and starts everything. Caddy issues the certificate on first boot."
