export type Role = 'owner' | 'member';

/** The languages the app writes in. Mirrors `web/src/language.ts`. */
export type Language = 'en' | 'de';

/** Mirrors `web/src/theme.tsx`. No attribute at all means "follow the device". */
export type Theme = 'light' | 'dark' | 'system';

export interface HouseholdRow {
  id: string;
  name: string;
  currency: string;
  created_at: string;
}

/**
 * An account. Deliberately says nothing about households — which ones a person
 * belongs to, what they are called there and what they may do lives in
 * `memberships`, because the answer differs per household.
 */
export interface UserRow {
  id: string;
  email: string;
  password_hash: string;
  /** Bumped on password change; session tokens carrying an older value are refused. */
  session_generation: number;
  /** NULL until the address is confirmed. */
  email_verified_at: string | null;
  /** Where a fresh sign-in lands. A convenience, never an access decision. */
  last_household_id: string | null;
  /**
   * What language this account reads *and* is written to in. It started as an
   * email-only setting, because the server has nobody to ask when it writes to
   * somebody who is not making the request; it now also decides what the
   * interface says, so the choice survives a browser losing its storage.
   */
  language: Language;
  /** What theme this account gets, on whatever it signs in to. */
  theme: Theme;
  /**
   * When this account last saved a pair of preferences, or NULL if it never
   * has. NULL is what lets the **device** win the first time, so nothing
   * changes under anyone the day this ships (migration `006`).
   */
  preferences_saved_at: string | null;
  created_at: string;
}

/** One account's place in one household: its name there, and its role. */
export interface MembershipRow {
  id: string;
  user_id: string;
  household_id: string;
  role: Role;
  display_name: string;
  created_at: string;
}

export interface EmailVerificationRow {
  token: string;
  user_id: string;
  expires_at: string;
  used_at: string | null;
  created_at: string;
}

export interface PasswordResetRow {
  token: string;
  user_id: string;
  created_by: string | null;
  expires_at: string;
  used_at: string | null;
  created_at: string;
}

export interface InviteRow {
  token: string;
  household_id: string;
  email: string | null;
  role: Role;
  created_by: string | null;
  expires_at: string;
  used_at: string | null;
  used_by: string | null;
  created_at: string;
}

export interface CategoryRow {
  id: string;
  household_id: string;
  name: string;
  color: string;
  monthly_budget_cents: number | null;
  created_at: string;
}

export interface ExpenseRow {
  id: string;
  household_id: string;
  category_id: string | null;
  paid_by: string | null;
  amount_cents: number;
  description: string;
  spent_on: string;
  /** Set when this row was generated by a recurring rule. */
  recurring_id: string | null;
  created_by: string | null;
  created_at: string;
}

export interface RecurringExpenseRow {
  id: string;
  household_id: string;
  category_id: string | null;
  paid_by: string | null;
  amount_cents: number;
  description: string;
  frequency: 'weekly' | 'monthly' | 'yearly';
  starts_on: string;
  ends_on: string | null;
  last_generated_on: string | null;
  is_active: number;
  created_by: string | null;
  created_at: string;
}

export interface ShoppingListRow {
  id: string;
  household_id: string;
  name: string;
  share_token: string | null;
  share_can_edit: number;
  created_by: string | null;
  created_at: string;
}

export interface ShoppingItemRow {
  id: string;
  list_id: string;
  name: string;
  quantity: string;
  /** The free-text comment on the item ("the blue box, not the red one"). */
  note: string;
  is_checked: number;
  added_by_name: string;
  checked_by_name: string | null;
  created_at: string;
  updated_at: string;
}

/**
 * One job on the household's to-do list.
 *
 * Unlike a shopping item, both "who" columns are FKs to accounts rather than
 * plain text: a to-do is never reachable through a share link, so there is no
 * guest whose name is only ever a label (`ARCHITECTURE.md` §3, §6).
 */
export interface TodoRow {
  id: string;
  household_id: string;
  title: string;
  is_done: number;
  created_by: string | null;
  done_by: string | null;
  done_at: string | null;
  created_at: string;
  updated_at: string;
}

/**
 * The signed-in account, attached by `requireAuth`.
 *
 * The household-shaped fields are nullable because a freshly registered
 * account has no household yet — that is the whole point of the two-step
 * sign-up. Routes that need one sit behind `requireHousehold`, which is what
 * lets `currentUser()` hand them the narrowed `SessionUser` below.
 */
export interface SessionAccount {
  id: string;
  email: string;
  emailVerified: boolean;
  /** The household being looked at right now, not "the" household. */
  householdId: string | null;
  /** Display name in the current household. */
  name: string | null;
  role: Role | null;
}

/**
 * An account known to be inside a household. Identical in shape to what every
 * household-scoped handler used before memberships existed, which is why those
 * handlers did not have to change: `householdId` still means "the household
 * this request is about".
 */
export interface SessionUser {
  id: string;
  householdId: string;
  email: string;
  emailVerified: boolean;
  name: string;
  role: Role;
}

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace Express {
    interface Request {
      user?: SessionAccount;
    }
  }
}
